title: 'Mimic by Mycroft and VocaliD'
author:
  name: 'Ryan Sipes'
  email: devops@mycroft.ai
taxonomies:
  - category
  - tag
metadata:
  description: 'Mimic by Mycroft and VocaliD'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
